env_name: ???
depth: ???
n_episodes: 5
debug_planner: True
render: False
seed: 42
save_actions: True
posinf: 100
neginf: -100
projection_fn: planners.projections:project_dummy
overwrite_ac_bounds: False
fallback: False
skip_search: False
adjust_lr: False
clip_grad: 1e-3

logic: FuzzyLogic
logic_kwargs: {weight: 10}
tnorm: ProductTNorm
tnorm_kwargs : {}


cem:
  n_samples: 200
  optimization_steps: 10
  elite_size: 20

mppi:
  n_samples: 2000
  optimization_steps: 10
  gamma: 1.0

complete:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam
  lrs_to_scan: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1]
  overwrite_lrs: False


sampling:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam
  lrs_to_scan: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1]
  overwrite_lrs: False


no_var:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam
  lrs_to_scan: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1]
  overwrite_lrs: False
