env_name: ???
depth: ???
n_episodes: 5
debug_planner: True
render: False
seed: 42
save_actions: True
posinf: 100
neginf: -100
projection_fn: planners.projections:project_dummy

logic: FuzzyLogic
logic_kwargs: {weight: 100}
tnorm: ProductTNorm
tnorm_kwargs : {}

mode: no_var

complete:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam

sampling:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam

no_var:
  step_size: 0.001
  step_size_var: 0.001
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  sop: numeric
  convergance_threshold: 0.1
  optimizer: adam