env_name: hvac
depth: 20

logic: FuzzyLogic
logic_kwargs: {weight: 10}

posinf: 5
neginf: 0

mode: no_var

complete:
  step_size: 10
  step_size_var: 10
  n_restarts: 2000

no_var:
  step_size: 0.5
  step_size_var: 0
  n_restarts: 200

sampling:
  step_size: 0.5
  step_size_var: 0
  n_restarts: 200