env_name: hvac
depth: 50
discrete: False

cem:
  n_samples: 200

mppi:
  n_samples: 200
  gamma: 1.0

disprod:
  step_size: 0.01
  step_size_var: 0.001
  n_restarts: 200
  taylor_expansion_mode: sampling