env_name: mars-rover
depth: 40
projection_fn: planners.projections:project_dummy

logic: FuzzyLogic
logic_kwargs: {weight: 10}

mode: no_var

complete:
  step_size: 0.01
  step_size_var: 0.001
  n_restarts: 200

sampling:
  step_size: 1
  step_size_var: 0.001
  n_restarts: 200

no_var:
  step_size: 1
  step_size_var: 0.001
  n_restarts: 200
