env_name: powergen
depth: 30

logic: FuzzyLogic
logic_kwargs: {weight: 10}

mode: no_var

complete:
  step_size: 0.0001
  step_size_var: 0.001
  n_restarts: 400
  optimizer: rmsprop

sampling:
  step_size: 0.1
  step_size_var: 1
  n_restarts: 200
  optimizer: rmsprop

no_var:
  step_size: 0.1
  step_size_var: 1
  n_restarts: 200
  optimizer: rmsprop