env_name: recsim
depth: 25
projection_fn: planners.projections:project_recsim

logic: FuzzyLogic
logic_kwargs: {weight: 5}

mode: sampling

complete:
  step_size: 10
  step_size_var: 1
  n_restarts: 200

sampling:
  step_size: 10
  step_size_var: 1
  n_restarts: 200

no_var:
  step_size: 10
  step_size_var: 1
  n_restarts: 200