env_name: reservoir-continuous
depth: 5

logic: FuzzyLogic
logic_kwargs: {weight: 20}

mode: no_var

complete:
  step_size: 1
  step_size_var: 0.1
  n_restarts: 2000

sampling:
  step_size: 1
  step_size_var: 0.1
  n_restarts: 2000

no_var:
  step_size: 1
  step_size_var: 0.1
  n_restarts: 2000
