env_name: uav
max_episode_steps: 200
depth: 15

logic: FuzzyLogic
logic_kwargs: {weight: 5}

mode: sampling

complete:
  step_size: 10
  step_size_var: 1
  n_restarts: 400

sampling:
  step_size: 10
  step_size_var: 1
  n_restarts: 400

no_var:
  step_size: 10
  step_size_var: 1
  n_restarts: 400